//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoyalCancun
{


    public partial class ManageReservations
    {

        /// <summary>
        /// PlaceReservation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RoyalCancun.ReservationManagement.PlaceReservation PlaceReservation;

        /// <summary>
        /// ChangeReservation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RoyalCancun.UserControls.ReservationManagement.ChangeReservation ChangeReservation;

        /// <summary>
        /// MyReservations control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::RoyalCancun.UserControls.ReservationManagement.MyReservations MyReservations;
    }
}
